# Generated by Django 4.0.6 on 2022-07-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_wallet', models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('client', 'Client')], default='person', max_length=10)),
                ('ewallet_reference_id', models.CharField(max_length=100)),
                ('ewallet_rapyd_id', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('phone_code', models.CharField(max_length=7)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=200)),
                ('address_rapyd_id', models.CharField(blank=True, max_length=80)),
                ('contact_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='person', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identification_type', models.CharField(blank=True, default='PA', max_length=3)),
                ('identification_number', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('cohabiting', 'Cohabiting'), ('not_applicable', 'Not_applicable')], default='not_applicable', max_length=14)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_applicable', 'Prefer not to tell')], default='not_applicable', max_length=14)),
                ('contact_rapyd_id', models.CharField(blank=True, max_length=50)),
                ('contact_url', models.CharField(blank=True, max_length=50)),
                ('verification_status', models.CharField(default='not verified', max_length=50)),
                ('wallets', models.ManyToManyField(to='individuals.wallet')),
            ],
        ),
    ]
