# Generated by Django 4.0 on 2022-07-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('identification_type', models.CharField(default='PA', max_length=3)),
                ('identification_number', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('cohabiting', 'Cohabiting'), ('not_applicable', 'Not_applicable')], default='Single', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('contact_id', models.CharField(max_length=50)),
                ('contact_url', models.CharField(max_length=50)),
                ('verification_status', models.CharField(default='not verified', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_wallet', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('ewallet_reference_id', models.CharField(max_length=100)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='individuals.account')),
            ],
        ),
    ]
