# Generated by Django 4.0.6 on 2022-07-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='GBP', max_length=5),
        ),
        migrations.CreateModel(
            name='Vbank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapyd_id', models.CharField(max_length=100)),
                ('merchant_reference_id', models.CharField(max_length=100)),
                ('ewallet_rapyd_id', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country_iso', models.CharField(max_length=5)),
                ('iban', models.CharField(max_length=100)),
                ('sort_code', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('bic', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=5)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individuals.wallet')),
            ],
        ),
    ]
