# Generated by Django 4.0 on 2022-07-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='identification_type',
            field=models.CharField(blank=True, default='PA', max_length=3),
        ),
    ]
