# Generated by Django 4.0.6 on 2022-07-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_account_currency_vbank_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='currency',
            new_name='currency_code',
        ),
    ]
