# Generated by Django 4.0.6 on 2022-07-29 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0003_rename_currency_account_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapyd_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=5)),
                ('vbank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individuals.wallet')),
            ],
        ),
    ]
