# Generated by Django 4.0 on 2022-07-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0003_alter_account_address_line_alter_account_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_code',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
