# Generated by Django 4.0 on 2022-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0004_account_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type_of_wallet',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=10),
        ),
    ]
