# Generated by Django 4.0.6 on 2022-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbank_account',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vbank_account',
            name='bic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vbank_account',
            name='iban',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vbank_account',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ewallet_rapyd_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
