# Generated by Django 4.0 on 2022-07-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0005_alter_wallet_type_of_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='phone_number',
        ),
    ]
