# Generated by Django 4.0 on 2022-07-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0006_remove_wallet_email_remove_wallet_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type_of_wallet',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=10),
        ),
    ]
