# Generated by Django 4.0 on 2022-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0008_alter_account_contact_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('client', 'Client')], default='person', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type_of_wallet',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=10),
        ),
    ]
