# Generated by Django 4.0 on 2022-07-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0010_alter_account_contact_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type_of_wallet',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('client', 'Client')], default='person', max_length=10),
        ),
    ]
