# Generated by Django 4.0 on 2022-07-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0012_alter_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=models.CharField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='country_name',
            field=models.CharField(default='United Sates', max_length=50),
            preserve_default=False,
        ),
    ]
