# Generated by Django 4.0 on 2022-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0013_remove_account_country_account_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='contact_id',
            new_name='contact_rapyd_id',
        ),
        migrations.AddField(
            model_name='account',
            name='address_rapyd_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ewallet_rapyd_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_applicable', 'Prefer not to tell')], default='not_applicable', max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('cohabiting', 'Cohabiting'), ('not_applicable', 'Not_applicable')], default='not_applicable', max_length=14),
        ),
    ]
